### ISSUE TITLE
Hostname verification

### ISSUE THREAD

**Issue by Archcry** [domibarton/docker-sabnzbd#18]
In de latest release of Sabnzbd (2.3.3) a new "feature" was introduced, [Hostname verification](https://sabnzbd.org/wiki/extra/hostname-check.html). You are now required to whitelist the domains you'd like to access sabnzbd from. I just updated to latest version and I am no longer able to access my sabnzbd instance. I get that simply adding the domain I run sabnzbd from resolves the issue but it might be a good idea to implement additional functionality in this image so people can add domain names via a environment variable?

> Add your host to host_whitelist in the Specials page of the Config. You can also edit the sabnzbd.ini directly.
> Only include the hostname, separate multiple values by ,

We can just accept one or multiple domain names (seperated with ,) as environment variable and edit sabnzbd.ini in the entrypoint of the container.

Let me know what you think.

**Comment by ssapalski** [comment]
You can create your docker instance with "-h my.domain.com". This doesn't need any special handling in container scripting. A README update would be sufficient?

I think patching sabnzbd.ini doesn't work in case of first time installation since it doesn't exist before sabnzbd was started.

**Comment by Archcry** [comment]
Hmm, the `-h` option might work for new installations but it did not work for my existing installation. I needed to manually add my domain in the config.ini.

**Comment by ssapalski** [comment]
I think for first time installations it is needed to create the docker container with appropriate "-h $HOSTNAME" parameter to let sabnzbd fill out host_whitelist automatically during installation. The container hostname can also be used for existing installations to patch "host_whitelist" if it isn't already included.

This will work for both use cases, first time installation and migration. In the case of migration users have to re-create the container:
  * docker rm $CONTAINER
  * docker create -h hostname ...

A solution with an environment variable doesn't cover first time installation but only the migration use case. My proposal with appropriate hostname + patching doesn't cover use cases where multiple hostnames would be needed. Are there any better and more simple solutions?

So far I haven't tried how sabnzbd behaves during first time installation if no appropriate hostname is set, does it install at all?

**Comment by Archcry** [comment]
I have never used a hostname in my docker-compose file, but I guess I patched the listen address manually after installing it for the first time.. We could still implement a way to patch the config.ini when it's present though, in the entrypoint, I don't know if this is what we want.

I think the only air-tight solution would be setting the hostname when first launching the image.

**Comment by nomadicj** [comment]
Any movement on this since this point guys? Just come up against it launcing from docker-compose. Would be lovely to just specify an environment var or something and not have to touch files inside the container.

**Comment by Archcry** [comment]
@nomadicj, what would you suggest as a suitable solution for this problem though?
