### ISSUE TITLE
Updating to 2.3.5

### ISSUE THREAD

**Issue by a10kiloham** [domibarton/docker-sabnzbd#24]
is this repo still live? would be nice to update to 2.3.5 if possible

**Comment by Archcry** [comment]
If you no longer want to maintain the project could you add maintainers? I wouldn't mind helping out!

**Comment by domibarton** [comment]
Yes it's still live, sorry for the delay!  
I've updated it to 2.3.5 with PR #23.

@Archcry I'd love to get some help :)

**Comment by Archcry** [comment]
Thanks :D

**Comment by Archcry** [comment]
Btw, how do I build the docker image, does it do that automatically on merge with master?

**Comment by a10kiloham** [comment]
It's automatic

**Comment by domibarton** [comment]
It's an automated Docker Hub build, which means:

- If a commit is pushed on `develop`, the `develop` Docker Image is built
- If a commit is pushed on `master`, the `latest` Docker Image is built
- If a tag is pushed, the tagged Docker Image is built

**Comment by Archcry** [comment]
Awesome!
