### ISSUE TITLE
Develop branch

### ISSUE THREAD

**Issue by Archcry** [domibarton/docker-sabnzbd#27]
What was the intention of the `develop` branch in this repository? Is it still needed and what was the ongoing development on this branch?

@domibarton

**Comment by domibarton** [comment]
I used to work with Gitflow, but I'm no longer a fan of it. Basically `develop` was latest greatest, feature branches were merged into it and for stable releases, the `develop` branch was merged into the `master` branch. Every commit on the `master` is then a release (that's basically a recap of it).

I propose to get rid of `develop` and start working with `master` again.

**Comment by domibarton** [comment]
I just had a look at the history. As the latest commits were merged directly into `master` instead of `develop`, I decided to remove `develop` and make `master` the default branch. This is the "default behaviour" on git/GitHub and probably works better for people not used to git or any workflows.

**Comment by Archcry** [comment]
I do like the git workflow and it would've come in handy with the recent upgrade to Debian buster as it's a big update with some uncertainties. Luckily it all worked out and we did not have any issues with that.
