### ISSUE TITLE
Dockerhub build seems broken

### ISSUE THREAD

**Issue by Archcry** [domibarton/docker-sabnzbd#33]
I made tag 2.3.9 and pushed master + develop build no build seem to run. Any idea what's wrong @domibarton?

**Comment by daniela-waranie** [comment]
See: https://github.com/domibarton/docker-sabnzbd/blob/develop/.travis.yml
```
docker tag ...
docker login
docker push ...
``` is in "after_success" section.
So my bet is that the image was pushed manually to hub.docker.com in the past.

**Comment by daniela-waranie** [comment]
If docker hub builder (autobuilds) was configured at hub.docker.com then you should visit that config page and check why it failed and maybe restart it.

**Comment by daniela-waranie** [comment]
Confirmed, you are using docker hub builder.
As one can see here: https://hub.docker.com/r/sabnzbd/sabnzbd/builds

Your last commit shows that there was a failure (red X next to your commit): 
https://github.com/domibarton/docker-sabnzbd/commits/master
...but the details page is not visable to me. I guess only @domibarton is the only one that has access permissions to that page.

**Comment by Archcry** [comment]
Unfortunately I am not able to see that page either..

**Comment by Archcry** [comment]
I updated the image to Debian Buster and made the Dockerfile a little cleaner in the process. I currently have version 2.3.9 up and running. Tag build should be finished soon!

**Comment by domibarton** [comment]
Thanks @Archcry, sorry for the delay.
