### ISSUE TITLE
Script Deobfuscate.py is missing execution permissions

### ISSUE THREAD

**Issue by itsikg** [domibarton/docker-sabnzbd#45]
I configured Sabnzbd to run Deobfuscate.py as a post download script. By default this script lacks execution permissions and the post processing fails with this error:
`Exit(-1) Cannot run script /sabnzbd/scripts/Deobfuscate.py
`
I fixed it manually by adding the permission, but since I'm using watchtower to auto update my containers, every time a new version is released the same problem returns.
Is is possible to fix the permissions in the container?

**Comment by Archcry** [comment]
Pull-request is linked, I'm just a bit uncertain whether it would be better to `chmod +x` all scripts in the scripts folder when the docker container starts (in `entrypoint.sh`) or just make the included `Deobfuscate.py` during the building process. Any thoughts?

**Comment by kruton** [comment]
During the buiding process should work fine.
