### ISSUE TITLE
DockerHub hasn't had a push in 10 months

### ISSUE THREAD

**Issue by Kangie** [domibarton/docker-sabnzbd#68]
3.5.3 release has been tagged in the repo but there are no images to pull from DockerHub.

I can see that CI actions publish to the GHCR automagically, but no documentation exists for using these images.

What's the preferred source for these docker images?

**Comment by Zixim** [comment]
so...is this now dead ?

**Comment by Kangie** [comment]
Any updates @kruton @domibarton

**Comment by Kangie** [comment]
#74
