### ISSUE TITLE
Should nzbToMedia be in the image?

### ISSUE THREAD

**Issue by kruton** [domibarton/docker-sabnzbd#7]
Frequently uses of SABnzbd use [nzbToMedia](https://github.com/clinton-hall/nzbToMedia) to notify various services when they have completed. My first thought was to just put this in the `/datadir`, but would this be more generally useful to have as part of the container image itself?

**Comment by Archcry** [comment]
I personally do not use it, but I investigated what it does and I can see the relevance of this plugin. I might even enable it when it's implemented in this image. The argument against implementing it is that this is a pure sabnzbd docker image.

**Comment by domibarton** [comment]
Mhm I personally don't use it, but it looks interesting. However, I don't know if we should add it to this image, or if we should create a new image. What do you guys think?

Are there any side effects / issues when we add it to this image? If we add it, we should still keep the sabnzbd versions, right? But what to do when we only want to update the nzbToMedia scripts?
